[Path]
# Assume that all user mail directories are directly under MailDir.  
# If this is not the case, please uncomment the lines below and configure UserDirectories.
#UserDirectories = [
#    '/mailu/mail/user1', 
#    '/mailu/mail/user2',
#    '/mailu/mail/user3'
#    ]

# If UserDirectories is uncommented, MailDir will not be read.
MailDir = '/mailu/mail/'

# Define the INBOX directory path relative to each user directory. 
# Assume that this relative path is consistent in all user directories.
InboxDirFromUserDir = 'cur'

# Define the junk directory path relative to each user directory. 
# Assume that this relative path is consistent in all user directories.
JunkDirFromUserDir = '.Junk/cur'