    # Assume that all user mail directories are directly under MailDir.
    # Also assume that the user mail directories are named with user email names.
    # If this is not the case, please uncomment the lines below and configure UserEmailsToDirectories.

    # Recording user emails is useful in creating a list of known sender
    # in the database for each of the users.

    # Indentation (tabs and/or spaces) is allowed but not required
    #[Path.UserEmailsToDirectories]
    #'user1@example.com' = '/mailu/mail/user1@example.com' 
    #'user2@example.com' = '/mailu/mail/user2@example.com'
    #'user3@example.com' = '/mailu/mail/user3@example.com'

[Path]
# If UserEmailsToDirectories is uncommented, MailDir will not be read.
MailDir = '/mailu/mail/'

# Define the INBOX directory path relative to each user directory. 
# Assume that this relative path is consistent in all user directories.
InboxDirFromUserDir = 'cur'

# Define the junk directory path relative to each user directory. 
# Assume that this relative path is consistent in all user directories.
JunkDirFromUserDir = '.Junk/cur'