################
#### For this configuration file, to better distinguish between configuration and comment,
#### 1 hashtag is used for configuration and 4 or more hashtags are used for comment.
################

domain: "michaelfong.co"

#### Recording user emails is useful in creating a list of known sender
#### in the database for each of the users.

#### Assume that all user mail directories are directly under mail_dir.
#### If this is not the case, please configure user_dirs.
path:
  mail_dir: "/mailu/mail/"
  #### user_dirs overrides mail_dir.
  # user_dirs:
  #   - "/mailu/mail/user1@example.com"
  #   - "/mailu/mail/user2@example.com"
  #   - "/mailu/mail/user3@example.com"

  #### Define the INBOX directory path relative to each user directory. 
  #### Assume that this relative path is consistent in all user directories.
  cur_inbox_dir_from_user_dir: "cur/"
  new_inbox_dir_from_user_dir: "new/"

  #### Define the junk directory path relative to each user directory. 
  #### Assume that this relative path is consistent in all user directories.
  cur_junk_dir_from_user_dir: ".Junk/cur/"
  new_junk_dir_from_user_dir: ".Junk/new/"

time:
  recognize_later_timer: 300.0
